### ISSUE TITLE
Pro Control "Post Picker" is limited to 5 posts being suggested based on full-text-search making other posts containing a word inaccessible

### ISSUE THREAD

**Issue by via-lars** [studiopress/genesis-custom-blocks#173]
## Bug summary  
  
Pro Control "Post Picker" is limited to 5 posts being suggested based on full-text-search **making other posts** containing a word entered **inaccessible**  
  
`wp-content\plugins\genesis-custom-blocks-pro\js\dist\block-editor-pro.js` contains a WP REST call using `per_page:5`. This is the culprit.  
  

## Steps to reproduce

1. Create a Genesis Custom Block using the Field Type "Post" and the Post Type "Posts".
2. Have more than 5 posts, each having a title different from one another, containing the word "hello" in their content.
3. Add the Genesis Custom Block from 1. to a post, search for "hello" in its "Post" field: you will be suggested 5 posts but you cannot access any other post
  
  
## Expected behavior  
  
All posts possibly in question are shown.  
  
  
## Actual behavior  
  
Only 5 posts are shown.  
  
  
## JS Console
  
No console errors present.  
  

## Additional information
  
none
  
  
## Suspected cause (optional)
  
Too low number in REST API call.  
  
  
## Versions

 - WordPress version: 6.4.1
 - Genesis Custom Blocks version: 1.6.0
 - Gutenberg plugin version (if active): -
 - Other block-related plugins (if active): -
 - OS: all
 - Browser: all
 - Device: all

**Comment by kienstra** [comment]
Hi @via-lars,
Thanks for pointing this out, you're right about it.

How many posts do you usually need to see? 

5 isn't enough, it sounds like.

Thanks!

**Comment by via-lars** [comment]
Hi @kienstra , in our particluar case it's a reference to an encyclopedia post type and the title of the post we want to reference is also used in around 20 posts as content text. As I guess you are using WP fulltextsearch everyone of those 20 posts would be found and hence 20 would be necessary to be shown in order to make sure the post having that word in the title is also visible.  
  
Theoretically there could be over 100 posts possibly in question but the WP REST API only supports 100 results per page and pagination is mandatory with that REST API. Thus 2 pagination page switch buttons below the autosuggest would be necessary no matter the amount actually shown. I guess around 10 to 20 entries visible at once in the autosuggest (or configurable) would be fitting.  
  
I thank you for taking care!

**Comment by chludwig** [comment]
Sorry for interfering.  
I guess most people want to search by title. Unfortunately it is not possible to search by title only using the WP API.  
So I would suggest to fetch at least 50 posts (limit fields to ID and post_title) and filter and/or order the results in the frontend so that posts that are having the search string in the title are displayed only or first.

**Comment by kienstra** [comment]
Hi @via-lars,
Thanks, could you please test this on a staging site?

[genesis-custom-blocks-pro.1.6.0.zip](https://github.com/studiopress/genesis-custom-blocks/files/13603827/genesis-custom-blocks-pro.1.6.0.zip)

It allows 10 suggestions, instead of 5:

![10-suggestions](https://github.com/studiopress/genesis-custom-blocks-pro/assets/4063887/dfd15b45-8957-4b17-846c-d1fcbe77bc40)

**Comment by kienstra** [comment]
Hi @chludwig,
Good point about searching by title.

Does this build help you, where it's now showing 10, instead of 5?

[genesis-custom-blocks-pro.1.6.0.zip](https://github.com/studiopress/genesis-custom-blocks/files/13603827/genesis-custom-blocks-pro.1.6.0.zip) (same as the one [linked to above](https://github.com/studiopress/genesis-custom-blocks/issues/173#issuecomment-1845924656))

>So I would suggest to fetch at least 50 posts (limit fields to ID and post_title) and filter and/or order the results in the frontend so that posts that are having the search string in the title are displayed only or first.

That's a good suggestion. But to be honest, we're not going to get to it.

Unfortunately, we're not focusing on the Genesis Custom Blocks plugins.

**Comment by via-lars** [comment]
@kienstra i'll see to have a look.  
  
Unofficially, can you give an outlook whether "you", respectively WPEngine, who also own ACF now, are pondering the idea to (continue to) offer a "Gutenberg Block creator" ?  
  
ACF also offers creating Gutenberg Blocks.  
  
A mix of the block creation and admin editor UI of GCB and the field possibilities of ACF (groups, dependencies, ...) would be a dream combination.  
  
I found the WP JS developer API gruesome. Their PHP is an outstanding example of AAA = anything anywhere anytime while adhering to the No 1 rule of who wannabe a market leader namely backwards compatibility. I would use words possibly deemed utmost negative to describe their JS API and developer "experience" so I refrain from continuing to write more about this.  
  
I and the team I'm in have been using GCB in 4 medium-sized company websites successfully over the past 3 years and were very happy about it.

**Comment by kienstra** [comment]
Hi @via-lars,
>I and the team I'm in have been using GCB in 4 medium-sized company websites successfully over the past 3 years and were very happy about it.

Thanks, that's high praise!

>A mix of the block creation and admin editor UI of GCB and the field possibilities of ACF (groups, dependencies, ...) would be a dream combination.

Sorry, we have no plans for that, and I don't think combining GCB and ACF will happen 😄 

>Unofficially, can you give an outlook whether "you", respectively WPEngine, who also own ACF now, are pondering the idea to (continue to) offer a "Gutenberg Block creator" ?

Yes, we're planning on continuing to support Genesis Custom Blocks, but not add new features.

I can't speak about ACF, as they're on a different team. 

But they have a lot more users, so they're probably going to have much more development than GCB.

**Comment by kienstra** [comment]
Hi @via-lars,
We'll release this fix in about 2 weeks to Genesis Custom Blocks Pro. Sorry for the delay.

**Comment by kienstra** [comment]
Hi @via-lars and @chludwig,
Could you please update to GCB Pro 1.6.1, and let me know if that works for you?

The [fix](https://github.com/studiopress/genesis-custom-blocks/issues/173#issuecomment-1845924656) for this issue is now deployed in GCB Pro 1.6.1.

You should see the update in `wp-admin/plugins.php` in the next 24 hours.

Thanks for your patience.

**Comment by kienstra** [comment]
The fix for this is deployed, so I'm closing this.
