### ISSUE TITLE
Does not work with Oxygen builder

### ISSUE THREAD

**Issue by Zyles** [studiopress/genesis-custom-blocks#99]
## Bug summary

Does not seem to work with [Oxygen Builder](https://oxygenbuilder.com/)

When saved it will look for `fake/blocks/block-.php`

![image](https://user-images.githubusercontent.com/1741593/143573476-4ee1d110-b591-4a6f-be42-37d3ac0778da.png)

The old version Block Lab worked just fine.

## Steps to reproduce

1. install Oxygen Builder
2. Install Genesis Custom Blocks
3. Create a new block and save
4. Points to invalid block PHP file

## Expected behavior

Should point to correct PHP file.

## Versions

 - WordPress version: 5.8.2
 - Genesis Custom Blocks version: 1.4.0

**Comment by Zyles** [comment]
After saving and going back to edit it displays correctly:

![image](https://user-images.githubusercontent.com/1741593/143573856-50d27fc2-9a0d-4434-96ed-1b23f51f81b7.png)

So maybe it is not Oxygen but some other bug.

The top menu is also above the builder menu:

![image](https://user-images.githubusercontent.com/1741593/143573913-c615cc83-c043-4ce9-b86e-7e8333d06db4.png)

**Comment by Aztec91** [comment]
Hey @Zyles it does work.

We use oxygen too.

Since Oxygen deletes all templates its kinda tricky to work with custom blocks.

The easiest way ist to install a theme that is called "blankslate", before you must use a plugin that is called "Oxygen Theme Enabler" you can find it if you google it.

We use it this way and it always works like a charm

**Comment by kienstra** [comment]
Thanks for opening this, sorry for the delay.

Closing this, as we aren't planning any development for it.
